import { spawn } from "node:child_process";
import { chromium } from "playwright-core";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const server = spawn(process.execPath, ["scripts/serve.js", "8139"], { cwd: root, stdio: "ignore" });
await new Promise((r) => setTimeout(r, 1200));
const browser = await chromium.launch({ channel: "msedge", headless: true });
const page = await browser.newPage({ viewport: { width: 900, height: 572 } });
page.on("pageerror", (e) => console.log("[pageerror]\n" + String(e.stack || e).slice(0, 600)));
await page.goto("http://localhost:8139/flower/?demo=1");
await page.waitForTimeout(2500);
await browser.close(); server.kill();
