import { chromium } from "playwright-core";
import path from "node:path";
import { fileURLToPath } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const browser = await chromium.launch({ channel: "msedge", headless: true });
const page = await browser.newPage({ viewport: { width: 900, height: 572 } });
const errs = [];
page.on("pageerror", (e) => errs.push(String(e).slice(0, 150)));
await page.goto("file:///" + path.join(root, "flower", "index.html").replace(/\\/g, "/") + "?demo=1");
await page.waitForFunction(() => window.__app && window.__app.renderMode === "particles" && window.__app.particles() > 80, { timeout: 20000 });
const p = await page.evaluate(() => window.__app.particles());
console.log("file:// 花朵单文件 OK: 粒子=" + p + " errors=" + errs.length);
if (errs[0]) console.log(errs[0]);
await browser.close();
